#
# Makefile for the fingerprint drivers.
#
obj-$(CONFIG_FINGERPRINT_GOODIX_TA)	+= goodix_ta/
obj-$(CONFIG_FINGERPRINT_FPC_TEE)	+= fpc_tee/
obj-$(CONFIG_FINGERPRINT_GOODIX_TA_CAPA)	+= goodix_ta_capa/
