obj-$(CONFIG_MSM_NPU)      := msm_npu.o
msm_npu-objs := npu_dev.o \
                npu_host_ipc.o \
                npu_hw_access.o \
                npu_mgr.o

obj-$(CONFIG_MSM_NPU_DEBUG_FS) += npu_debugfs.o npu_dbg.o
